spring:
    web:
        error:
            include-message: always
            include-binding-errors: always
    datasource:
        password: # your password
        url: # your url
        username:  # your username
        
    jpa:
        hibernate:
            ddl-auto: update
        properties:
           hibernate:
               dialect: org.hibernate.dialect.PostgreSQLDialect
               format_sql: true
        show-sql: true