spring:
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect 
    show-sql: true
  
server:
  address: ${MAIN_HOST:127.0.0.1}
  port: ${MAIN_PORT:8080}

app:
  public-url: http://${MAIN_HOST}:${MAIN_PORT}
